import { createComponent as createReactComponent, EventName, Options, ReactWebComponent } from "@lit/react";

type EventNames = Record<string, EventName | string>;

/**
 * Creates an SSR-safe React component for a custom element. Properties are distinguished
 * from attributes automatically, and events can be configured so they are added
 * to the custom element as event listeners.
 *
 * @param options An options bag containing the parameters needed to generate a
 * wrapped web component.
 *
 * @param options.react The React module, typically imported from the `react`
 * npm package.
 * @param options.tagName The custom element tag name registered via
 * `customElements.define`.
 * @param options.elementClass The custom element class registered via
 * `customElements.define`.
 * @param options.events An object listing events to which the component can
 * listen. The object keys are the event property names passed in via React
 * props and the object values are the names of the corresponding events
 * generated by the custom element. For example, given `{onactivate:
 * 'activate'}` an event function may be passed via the component's `onactivate`
 * prop and will be called when the custom element fires its `activate` event.
 * @param options.displayName A React component display name, used in debugging
 * messages. Default value is inferred from the name of custom element class
 * registered via `customElements.define`.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export function createComponent<I extends HTMLElement, E extends EventNames = {}>({
  react,
  tagName,
  elementClass,
  events,
  displayName,
}: Options<I, E>): ReactWebComponent<I, E> {
  return typeof window !== "undefined"
    ? createReactComponent<I, E>({ react, tagName, elementClass, events, displayName })
    : <ReactWebComponent<I, E>>(<unknown>null);
}
