import resolve from "@rollup/plugin-node-resolve";
import terser from "@rollup/plugin-terser";
import typescript from "@rollup/plugin-typescript";
import babel from "@rollup/plugin-babel";
import createConfig from "../../rollup.config.js";

const inputs = [
  "core",
  "core/a11y",
  "core/anchoring",
  "core/bidi",
  "core/layout",
  "core/platform",
  "app-bar",
  "autocomplete",
  "avatar",
  "badge",
  "bottom-sheet",
  "button",
  "button-group",
  "card",
  "checkbox",
  "chips",
  "dialog",
  "divider",
  "drawer-container",
  "expansion-panel",
  "fab",
  "fab-menu",
  "form-field",
  "heading",
  "icon",
  "icon-button",
  "list",
  "loading-indicator",
  "menu",
  "nav-bar",
  "nav-menu",
  "nav-rail",
  "option",
  "paginator",
  "progress-indicator",
  "radio-group",
  "segmented-button",
  "select",
  "shape",
  "slide-group",
  "slider",
  "snackbar",
  "split-button",
  "stepper",
  "switch",
  "tabs",
  "textarea-autosize",
  "theme",
  "toc",
  "toolbar",
  "tooltip",
];

export default createConfig({ 
  inputs: inputs, 
  externals: [ /^@m3e\//, /^lit$/, /^lit\//, /^@lit\/reactive-element$/, /^@lit\/reactive-element\// ],
});

