import { customElementVsCodePlugin } from "custom-element-vs-code-integration";

export default {
  globs: [
    "src/**/*.ts",
    "../core/src/**/*.ts",
    "../app-bar/src/**/*.ts",
    "../badge/src/**/*.ts",
    "../button/src/**/*.ts",
    "../button-group/src/**/*.ts",
    "../card/src/**/*.ts",
    "../checkbox/src/**/*.ts",
    "../chips/src/**/*.ts",
    "../dialog/src/**/*.ts",
    "../divider/src/**/*.ts",
    "../drawer-container/src/**/*.ts",
    "../expansion-panel/src/**/*.ts",
    "../fab/src/**/*.ts",
    "../fab-menu/src/**/*.ts",
    "../form-field/src/**/*.ts",
    "../heading/src/**/*.ts",
    "../icon/src/**/*.ts",
    "../icon-button/src/**/*.ts",
    "../list/src/**/*.ts",
    "../loading-indicator/src/**/*.ts",
    "../menu/src/**/*.ts",
    "../nav-bar/src/**/*.ts",
    "../nav-menu/src/**/*.ts",
    "../nav-rail/src/**/*.ts",
    "../progress-indicator/src/**/*.ts",
    "../radio-group/src/**/*.ts",
    "../segmented-button/src/**/*.ts",
    "../shape/src/**/*.ts",
    "../slide-group/src/**/*.ts",
    "../stepper/src/**/*.ts",
    "../slider/src/**/*.ts",
    "../snackbar/src/**/*.ts",
    "../split-button/src/**/*.ts",
    "../switch/src/**/*.ts",
    "../tabs/src/**/*.ts",
    "../textarea-autosize/src/**/*.ts",
    "../theme/src/**/*.ts",
    "../toc/src/**/*.ts",
    "../toolbar/src/**/*.ts",
    "../tooltip/src/**/*.ts",
  ],
  exclude: ["src/**/*.spec.ts"],
  packagejson: true,
  outdir: "dist",
  litelement: true,
  plugins: [
    customElementVsCodePlugin({
      outdir: "dist",
      htmlFileName: "html-custom-data.json",
      cssFileName: "css-custom-data.json",
    }),
  ],
};
